### ISSUE TITLE
WAW fails to load

### ISSUE THREAD

**Issue by diegodevalera** [triplea-maps/world_at_war#2]
Hello, apologies if this is the wrong forum.  I have recently migrated from TripleA 1.8.0.9 to 1.9.0.0.3453 and have had no trouble playing any of the maps except WAW.  After I click play for a local game of WAW, the "loading game, please wait" dialog box appears for a few seconds, and then I am returned to the player selection screen.  This also occurs for WAW 1940, but not any of the WAW "variants" in the Experimental tab of the map downloader.   I have attached the [log](https://github.com/triplea-maps/world_at_war/files/678497/console.txt) from the java console.   Thanks in advance!

**Comment by ron-murhammer** [comment]
@diegodevalera It appears you have a corrupted map download. Please try deleting the existing WaW map zip and redownload it.
